### ISSUE TITLE
0.7.0 `x11-clipboard` hangs

### ISSUE THREAD

**Issue by kchibisov** [quininer/x11-clipboard#33]
After we've updated to 0.7.0 version in alacritty, it was reported that this crate hangs when doing clipboard operations.

https://github.com/alacritty/alacritty/issues/6760

**Comment by kchibisov** [comment]
We simply updated because the `quick_xml` used by `0.6.0` had future incompatible code and was constantly throwing a warning.

We'll downgrade if it won't get resolved before the release.

**Comment by MarcusGrass** [comment]
Managed to reproduce it, I think the old x11-library added a nullterminator to the provided string. 
I can reproduce this by just running an example where I store a value into the clipboard and then try to paste it into Brave, it indeed hangs. 
If I add a null terminator it doesn't anymore, I'm going to see if I can produce a nice fix.

**Comment by MarcusGrass** [comment]
I'm still digging, we're ending up in a loop where brave freezes while continuously asking for different targets to be set on the `CHROME_SELECTION` property, which we do but it doesn't quite seem to stick.   

Something that's a bit off is that in the case of applications that seem to be handling this alright, the incoming request time is set, but in Brave's case it's 0.  
Since it works on 0.6 it's not Brave's fault but I'm wondering what might have changed under the hood to cause this behaviour, I've been looking through the change and it seems to be 1-to-1 the same at least on the API invocations between x11rb and the xcb-c-bindings used before. I'm looking closer into that at the moment

**Comment by MarcusGrass** [comment]
Okay, It turned out to be a simple refactoring mistake and an easy fix, got a PR up for it. 

It was nothing under the hood, definitely not Brave's fault, just a bad refactor that was pretty difficult to spot, I built alacritty against it and it works as expected now. Sorry!

**Comment by kchibisov** [comment]
Thanks!
